import { auth } from "@/auth";
import AppSidebar from "@/components/navigation/sidebar";
import { SidebarInset, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Session } from "next-auth";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null = await auth();

  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <AppSidebar user={session?.user} />
          <SidebarInset className="p-3">
            <SidebarTrigger />
            {children}
          </SidebarInset>
        </Providers>
      </body>
    </html>
  );
}
